<a href="https://colab.research.google.com/github/Mohammad-Ab/Python-Graphic/blob/main/MatrixEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#number 1
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(int(x/2)):
    array[[2*i,2*i+1]] = array[[2*i+1,2*i]]
  print(array)

main()


please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[1 2 2 9]
 [3 7 2 3]
 [6 3 4 8]
 [8 1 1 2]]
--------------------------------
[[3 7 2 3]
 [1 2 2 9]
 [8 1 1 2]
 [6 3 4 8]]


In [ ]:
#number 2
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(int(x/2)):
    array[: , [2*i,2*i+1]] = array[: , [2*i+1,2*i]]
  print(array)

main()

please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[1 0 4 5]
 [7 1 4 1]
 [6 2 4 9]
 [6 4 9 0]]
--------------------------------
[[0 1 5 4]
 [1 7 1 4]
 [2 6 9 4]
 [4 6 0 9]]


In [ ]:
#number 3
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(int(x/2)):
    array[[2*i,2*i+1]] = array[[2*i+1,2*i]]
  
  for i in range(int(x/2)):
    array[: , [2*i,2*i+1]] = array[: , [2*i+1,2*i]]
  print(array)

main()

please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[7 4 5 4]
 [3 8 5 2]
 [1 0 3 3]
 [2 9 9 4]]
--------------------------------
[[8 3 2 5]
 [4 7 4 5]
 [9 2 4 9]
 [0 1 3 3]]


In [ ]:
#number 4
import numpy as np
def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(int(x/2)):
    array[: , [2*i,-1*i+3]] = array[: , [-1*i+3,2*i]]
  print(array)

main()


please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[0 7 6 6]
 [6 5 4 3]
 [1 6 0 7]
 [5 7 3 3]]
--------------------------------
[[6 7 6 0]
 [3 5 4 6]
 [7 6 0 1]
 [3 7 3 5]]


In [ ]:
#number 5
import numpy as np
def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(int(x/2)):
    array[[2*i,-1*i+3],:] = array[[-1*i+3,2*i],:]
  print(array)

main()


please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[0 7 8 0]
 [6 1 7 8]
 [6 2 0 4]
 [4 4 3 3]]
--------------------------------
[[4 4 3 3]
 [6 1 7 8]
 [6 2 0 4]
 [0 7 8 0]]


In [ ]:
#number 6
import numpy as np
def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(x):
    if i%2 == 0:
      array[i]+=1
    else:
      array[i]-=1
  print(array)

main()

please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[3 6 6 8]
 [5 5 2 9]
 [7 2 0 0]
 [5 6 1 3]]
--------------------------------
[[4 7 7 9]
 [4 4 1 8]
 [8 3 1 1]
 [4 5 0 2]]


In [ ]:
#number 7
import numpy as np
def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(x):
    for j in range(y):
      if array[i][j]%2 == 0:
        array[i][j]/=2
      else:
        array[i][j]+=1
  print(array)


main()

please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[5 3 4 2]
 [6 9 3 1]
 [6 4 0 1]
 [4 2 6 9]]
--------------------------------
[[ 6  4  2  1]
 [ 3 10  4  2]
 [ 3  2  0  2]
 [ 2  1  3 10]]


In [ ]:
#number 11
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  i=int(input("please enter a row:"))
  j=int(input("please enter anoter row:"))
  array[[i-1,j-1]] = array[[j-1,i-1]]
  print("-------------------")
  print(array)
main()


please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[2 8 5 6]
 [5 1 2 7]
 [2 7 3 8]
 [9 2 1 7]]
--------------------------------
please enter a row:2
please enter anoter row:3
-------------------
[[2 8 5 6]
 [2 7 3 8]
 [5 1 2 7]
 [9 2 1 7]]


In [ ]:
#number 12
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)

def cal(array,x,y):
  print("the array before make opration")
  print(array)
  new_array = np.random.rand(x,y)
  print("new random array between 0 & 1:")
  print(new_array)
  for i in range(x):
    for j in range(y):
      if new_array[i][j] > 0.5:
        array[i][j]+=1
      else:
        array[i][j]-=1
  print("-------------")
  print(array)



main()

please enter number of your row:4
please enter number of your columns:4
the array before make opration
[[3 7 8 8]
 [6 6 8 5]
 [3 1 5 4]
 [7 8 4 4]]
new random array between 0 & 1
[[0.94907865 0.17767049 0.9768638  0.42293169]
 [0.43933877 0.23857626 0.21397749 0.87103518]
 [0.27321981 0.35563427 0.753107   0.07495353]
 [0.21198347 0.87632371 0.98699261 0.75971135]]
-------------
[[4 6 9 7]
 [5 5 7 6]
 [2 0 6 3]
 [6 9 5 5]]


In [ ]:
#number 13
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  array = array.reshape(x*y,1)
  print(array)
  print("-------------")
  n = len(array)
  '''for i in range(n-1):
    for j in range(0, n-i-1):
      if array[j] > array[j + 1]:
        swapped = True
        array[j], array[j + 1] = array[j + 1], array[j]
      if not swapped:
          return'''
  for i in range(n):
    for j in range(0, n - i - 1):
      if array[j] > array[j + 1]:
        temp = array[j]
        array[j] = array[j+1]
        array[j+1] = temp
        del temp

  print("array sorted with bubble sort")
  print(array)
  print("-----------------------------")
  array = array.reshape(x,y)
  print(array)

main()

please enter number of your row:2
please enter number of your columns:2
the array before make opration
[[1 4]
 [6 8]]
--------------------------------
[[1]
 [4]
 [6]
 [8]]
-------------
array sorted with bubble sort
[[1]
 [4]
 [6]
 [8]]
-----------------------------
[[1 4]
 [6 8]]


In [ ]:
#number 16
import numpy as np
import math

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(20, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  for i in range(x):
    for j in range(y):
      if array[i][j] >= 10:
        array[i][j]/=2
      else:
        array[i][j] = math.sqrt(array[i][j])

  print(array)

main()


please enter number of your row:3
please enter number of your columns:3
the array before make opration
[[13 16 11]
 [ 9  2 19]
 [ 1 17  1]]
--------------------------------
[[6 8 5]
 [3 1 9]
 [1 8 1]]


In [ ]:
#number 17
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)

def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("-------------------------------")
  for i in range(x):
    for j in range(y):
      array[i][j] = 50 #our formula in question is 2x+10-2x+40 => 50

  print(array)

main()

please enter number of your row:2
please enter number of your columns:2
the array before make opration
[[6 1]
 [9 6]]
-------------------------------
[[50 50]
 [50 50]]


In [ ]:
#number 20
import random

def main():
  x=int(input("please enter a number for len list:"))
  list1=[]
  for i in range(x):
    n=random.randint(1,10)
    list1.append(n)
  print(list1)
  cal(list1,x)
def cal(list1,x):
  new_list1=[]
  new_list2=[]
  for i in range(x-1):
    y=list1[i]+list1[i+1]
    y/=2
    new_list1.append(y)
    z=list1[i]-list1[i+1]
    z/=2
    new_list2.append(z)
  print(new_list1)
  print(new_list2)

main()

please enter a number for len list:4
[8, 5, 4, 5]
[6.5, 4.5, 4.5]
[1.5, 0.5, -0.5]


In [ ]:
#number 21
import random

def main():
  x=int(input("please enter a number for len list:"))
  list1=[]
  for i in range(x):
    n=random.randint(1,10)
    list1.append(n)
  print(list1)
  cal(list1,x)
def cal(list1,x):
  new_list1=[]
  new_list2=[]
  for i in range(int(x/2)):
    y=list1[2*i]+list1[2*i+1]
    y/=2
    new_list1.append(y)
    z=list1[2*i+1]-list1[2*i]
    new_list2.append(z)
  print(new_list1)
  print(new_list2)

main()

please enter a number for len list:4
[6, 10, 7, 10]
[8.0, 8.5]
[4, 3]


In [ ]:
#number 22
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  array=array.astype(float)
  z=array.max()
  for i in range(x):
    for j in range(y):
      array[i][j] = array[i][j] / z
  print(array)

main()

please enter number of your row:3
please enter number of your columns:3
the array before make opration
[[8 4 1]
 [8 7 8]
 [7 0 3]]
--------------------------------
[[1.    0.5   0.125]
 [1.    0.875 1.   ]
 [0.875 0.    0.375]]


In [ ]:
#number 23

import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  print("our array before operation")
  print(array)
  print("--------------------------")
  cal(array,x,y)
def cal(array,x,y):
  array=array.astype(float)
  for i in range(y):
    z=array.max(axis=0)
    array[:,i] = array[:,i]/z
  print(array)

main()

please enter number of your row:3
please enter number of your columns:3
our array before operation
[[6 9 4]
 [7 0 9]
 [5 2 7]]
-----------
[[ 0.85714286 10.5         4.66666667]
 [ 0.77777778  0.          0.85714286]
 [ 0.55555556  0.22222222  0.77777778]]


In [ ]:
#number 28
import numpy as np

def main():
  x=int(input("please enter number for our rows and columns:"))
  array=np.random.rand(x,x)
  print("array before operation:")
  print(array)
  print("-----------------------")
  cal(array,x)
def cal(array,x):
  for i in range(x):
    for j in range(x):
      if array[i][j] < 0.2:
        array[i][j] = 0
      else:
        array[i][j] = 1
  array=array.astype(int)
  print(array)

main()

please enter number for our rows and columns:2
array before operation:
[[0.69220308 0.90978468]
 [0.3051055  0.7632946 ]]
-----------------------
[[1 1]
 [1 1]]


In [ ]:
#number 45
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  array2 = np.random.randint(10, size=(x,y))
  cal(array,array2,x,y)
def cal(array,array2,x,y):
  print("the first array before make operation:")
  print(array)
  print("the second array before make operation:")
  print(array2)
  print("--------------------------------")
  s=(x,y)
  new_array=np.zeros(s)
  for i in range(x):
    for j in range(y):
      if array[i][j]> array2[i][j]:
        new_array[i][j] = array[i][j]
      else:
        new_array[i][j] = array2[i][j]

  print(new_array)

main()

please enter number of your row:4
please enter number of your columns:4
the first array before make operation:
[[7 2 1 2]
 [9 7 5 5]
 [0 6 4 5]
 [2 3 2 8]]
the second array before make operation:
[[8 5 6 2]
 [6 0 0 9]
 [0 5 4 5]
 [8 3 9 1]]
--------------------------------
[[8. 5. 6. 2.]
 [9. 7. 5. 9.]
 [0. 6. 4. 5.]
 [8. 3. 9. 8.]]


In [ ]:
#number 18
import numpy as np
def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  cal(array,x,y)
def cal(array,x,y):
  print("the array before make opration")
  print(array)
  print("--------------------------------")
  s=(2*x,2*y)
  new_array=np.zeros(s)
  for i in range(x):
    for j in range(2*x):
      if j < 2:
        new_array[i][j] = array[0][0]
      else:
        new_array[i][j] = array[0][1]
  for i in range(2*x):
    if i >= 2:
      for j in range(2*x):
        if j < 2:
          new_array[i][j] = array[1][0]
        else:
          new_array[i][j] = array[1][1]
  print(new_array)    
main()

please enter number of your row:2
please enter number of your columns:2
the array before make opration
[[5 7]
 [1 8]]
--------------------------------
[[5. 5. 7. 7.]
 [5. 5. 7. 7.]
 [1. 1. 8. 8.]
 [1. 1. 8. 8.]]


In [ ]:
#number 25
import numpy as np

def main():
  x=int(input("please enter number of your row:"))
  y=int(input("please enter number of your columns:"))
  array = np.random.randint(10, size=(x,y))
  array2= np.random.randint(10, size=(x,y))
  cal(array,array2,x,y)
def cal(array,array2,x,y):
  print("the first array")
  print(array)
  print("the second array")
  print(array2)
  print("--------------------------------")
  s=(x,y)
  new_array=np.zeros(s)
  for i in range(x):
    for j in range(y):
      if j%2 == 0:
        new_array[i][j] = array[i][j]
      else:
        new_array[i][j] = array2[i][j]
  print(new_array)
main()

please enter number of your row:3
please enter number of your columns:3
the first array
[[8 0 2]
 [7 4 3]
 [4 2 3]]
the second array
[[9 0 8]
 [7 8 8]
 [0 2 8]]
--------------------------------
[[8. 0. 2.]
 [7. 8. 3.]
 [4. 2. 3.]]
